
crontime: "0 3 * * *"    ## run cronjob every day at 3 AM (time hr: 0-23 )

auditsweeper:
  configmaps:
    db:
      db-port: '5432'
      db-su-user: 'postgres'
      db-host: 'postgres.sandbox.mosip.net'
    auditsweeper:
      log-age-days: '90'

